### PR TITLE
fix: send email to only users subscribed to the given email type

### LINKED ISSUE #80: feat(email sending): need to send email only to users with subscription
Discussed [in comment](https://github.com/snapshot-labs/envelop/pull/53/files#r1200808622)

Currently, we send emails to all subscribed users despite the subscription user being subscribed.

We should query only users with appropriate subscriptions from DB for sending emails.

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

All emails are sent to all users, regardless of their subscription preferences

## 💊 Fixes / Solution

Fix #80 

Users should only receive email types they have subscribed to

## 🚧 Changes

- Add filter before sending each email type, to send it to only emails subscribed to the given email type

## 🛠️ Tests

- Currently hard to test, only way know is to console.log ` await getVerifiedSubscriptions('summary');` somewhere in your code (and change the args to other email type), and see that it returns the correct database row. Requires your test DB to be populated with some test data.

More robusts tests will come later

### CODE REVIEW

File: src/helpers/utils.ts [hunk 1]
```diff
@@ -131,13 +131,15 @@ export async function unsubscribe(email: string, address: string) {
...
+export async function getVerifiedSubscriptions(subscription: string, batchSize = 1000) {
   let page = 0;
   let results: SqlRow[] = [];
+  const sub = sanitizeSubscriptions(subscription)[0];
 
   while (true) {
     const result = await db.queryAsync(
-      'SELECT email, address FROM subscribers WHERE verified > 0 ORDER BY created LIMIT ? OFFSET ?',
+      'SELECT email, address, subscriptions FROM subscribers WHERE verified > 0 ' +
+        `AND JSON_CONTAINS(subscriptions, '"${sub}"') ORDER BY created LIMIT ? OFFSET ?`,
```
Comment (ChaituVR) [inline src/helpers/utils.ts:142]: I think better to use `?` . though we are already sanitizing `sub`, using `?` makes the code look more clear and secure :)

**Review by ChaituVR — CHANGES_REQUESTED** [review]

File: src/helpers/utils.ts (hunk 1 above)
Comment (wa0x6e) [reply src/helpers/utils.ts:142]: I think so too, but I haven't been able to get it working, because of the JSON escaping. Can you propose a change ?

File: src/helpers/utils.ts [hunk 2]
```diff
@@ -131,13 +131,15 @@ export async function unsubscribe(email: string, address: string) {
...
       [batchSize, page * batchSize]
```
Comment (Todmy) [inline src/helpers/utils.ts:143]: try this
```suggestion
      'SELECT email, address, subscriptions FROM subscribers WHERE verified > 0 ' +
        `AND JSON_CONTAINS(subscriptions, ?) ORDER BY created LIMIT ? OFFSET ?`,
      [JSON.stringify(sub), batchSize, page * batchSize]
```

**Review by Todmy — CHANGES_REQUESTED** [review]

File: src/helpers/utils.ts (hunk 1 above)
Comment (Todmy) [reply src/helpers/utils.ts:142]: the problem with this approach is that when a user subscribes the first time we leave `subscription` column entry value equal to null and handle that [here](https://github.com/snapshot-labs/envelop/blob/c86363476375d42ae979c71f2a50a6c024457d50/src/helpers/utils.ts#L177). Since we leave the value empty, this query will not select those users (which haven't updated subscription at least once), but it should.

Comment (wa0x6e) [reply src/helpers/utils.ts:142]: Correct, will look into that

Comment (wa0x6e) [reply src/helpers/utils.ts]: Fixed, now taking into account `NULL` subscriptions.

**Review by Todmy — APPROVED** [review]
tACK

**Comment by wa0x6e** [comment]
@ChaituVR are you OK with the fix ?

**Review by Todmy — APPROVED** [review]
tACK
