### PR TITLE
fix: fix missing `salt` in email verification link

### LINKED ISSUE #126: fix(email verify): email verification fails all the time
### Issue Description:
The issue arises in the context of a new property named `salt`. 

In our codebase, there is an inconsistency regarding the parameters passed to the query.

- In [this section of the code](https://github.com/snapshot-labs/envelop/blob/e163a72b134691097c932b308c69348f57afcf04/src/templates/subscribe/index.ts#L7), we are passing only three parameters to the query, namely: `signature`, `email`, and `address`.

- However, in [another part of the code](https://github.com/snapshot-labs/envelop/blob/e1ba8484c4c28d400169d8d93a5c4da64645e7a1/src/rpc.ts#LL48C1-L48C1), we are expecting four parameters: `signature`, `email`, `address`, and `salt`.

This inconsistency results in a persistent failure in email validation.

### Steps to Reproduce:
1) Subscribe with an email.
2) Try to validate the email address through the email letter that was sent to you.

### Expected Behavior:
A user should be able to validate email.

### Actual Behavior:
It is currently impossible to validate email.

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

Email verification link is missing the `salt` params, making all verification link fail

## 💊 Fixes / Solution

Fix #126 

Add the missing `salt` params to verification link

## 🚧 Changes

- Inject the missing `salt` link to all verification links

## 🛠️ Tests

- Go to `/preview/verify`. The verify link should contains the `salt` param
- You can also test sending yourself an email with the `send-subscribe` scripts. 

If you want to test the whole workflow with envelop-ui, test with the PR https://github.com/snapshot-labs/envelop-ui/pull/17

### CODE REVIEW

File: src/templates/subscribe/index.ts [hunk 1]
```diff
@@ -6,7 +6,8 @@ export default async function prepare(params: TemplatePrepareParams) {
   const verifyLink = `${process.env.FRONT_HOST}/#/verify?${new URLSearchParams({
     signature: await signVerify(params.to, params.address, params.salt),
```
Comment (Todmy) [inline src/templates/subscribe/index.ts:7]: Here we have a type-matching problem. If you check `typeof params.salt` at this line you will get `number`. But since we send it as a part of the URL query, it will implicitly be converted to a string, and at `envelop-ui` project the `typeof route.query.salt` will return the string. Respectively during `verifyVerify` function we always will get `false` since we signed the message with salt type `number`, but verifying it with salt type `string`

**Review by Todmy — CHANGES_REQUESTED** [review]

**Review by Todmy — APPROVED** [review]
tACK
